services:
  garage:
    image: dxflrs/garage:v0.9.0
    container_name: garage
    restart: always
    ports:
      - "127.0.0.1:3900:3900" # S3 API — только localhost
      - "127.0.0.1:3901:3901" # RPC (внутренняя связь) — только localhost
      - "127.0.0.1:3902:3902" # Admin API — только localhost
    environment:
      - GARAGE_ALLOW_WORLD_READABLE=1
    volumes:
      - ./garage_data:/var/lib/garage
      - ./garage.toml:/etc/garage.toml

  postgres:
    image: postgres:16-alpine
    container_name: photoservices_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: MoeL1obimoe96ivotnoe-Din0
      POSTGRES_DB: photoservices_db
    ports:
      - "127.0.0.1:5433:5432" # PostgreSQL — только localhost
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: photoservices_backend
    restart: unless-stopped
    ports:
      - "127.0.0.1:3000:3000"
    env_file:
      - ./backend/.env   # читает все переменные из .env
    environment:
      HOST: "0.0.0.0"
      DB_HOST: "postgres"
      DB_PORT: "5432"
      DATABASE_URL: "postgresql://postgres:MoeL1obimoe96ivotnoe-Din0@postgres:5432/photoservices_db"
      S3_ENDPOINT: "http://garage:3900"
      AI_SERVICE_URL: "http://ai-service:8001"
      BACKEND_INTERNAL_URL: "http://backend:3000"
    depends_on:
      - postgres
      - garage

  ai-service:
    build:
      context: ./ai-service
      dockerfile: Dockerfile
    container_name: photoservices_ai
    restart: "no"
    ports:
      - "127.0.0.1:8001:8001"
    volumes:
      - ./ai-service/weights:/app/weights
      - huggingface_cache:/root/.cache/huggingface
    environment:
      CLIP_MODEL_NAME: "openai/clip-vit-base-patch32"
      CLIP_WEIGHTS_PATH: "weights/clip_finetuned.pt"

volumes:
  postgres_data:
  huggingface_cache:
